# Generated by Django 6.0.2 on 2026-03-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='age',
        ),
        migrations.AddField(
            model_name='animal',
            name='age_months',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='animal',
            name='age_years',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='animal',
            name='category',
            field=models.CharField(default='Pets', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='animals/'),
        ),
        migrations.AddField(
            model_name='animal',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('healthy', 'Healthy'), ('sick', 'Sick'), ('critical', 'Critical')], default='healthy', max_length=20),
        ),
    ]
